apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: default
spec:
  selector:
    app: wisecow-nginx
  ports:
    - protocol: TCP
      port: 4499       # port inside cluster
      targetPort: 4499 # container port
  type: ClusterIP
